name: covid19
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  intl: ^0.16.1
  charts_flutter: ^0.9.0
  sqflite: ^1.3.0
  connectivity: ^0.4.8+2
  shared_preferences: ^0.5.7
  cupertino_icons: ^0.1.2
  expandable: ^4.1.3
  flutter_bloc: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true